# Generated by Django 5.0.4 on 2024-05-16 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('experience', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=30)),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_hobbies', models.ManyToManyField(to='booking_app.hobby')),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('stars', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('rating', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelOwner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking_app.user')),
                ('owner_exp_status', models.PositiveIntegerField(null=True)),
            ],
            bases=('booking_app.user',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking_app.user')),
                ('guest_rating', models.PositiveIntegerField(null=True)),
            ],
            bases=('booking_app.user',),
        ),
        migrations.AddField(
            model_name='hobby',
            name='owners',
            field=models.ManyToManyField(related_name='hobbies', to='booking_app.user'),
        ),
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_time', models.DateTimeField(auto_now_add=True)),
                ('detail', models.CharField(max_length=200, null=True)),
                ('hotels', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking_app.hotels')),
            ],
        ),
        migrations.CreateModel(
            name='HotelsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('time_comment', models.DateTimeField(auto_now_add=True)),
                ('hotel_rating', models.PositiveIntegerField(null=True)),
                ('hotels', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_comments', to='booking_app.hotels')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('id_card_number', models.IntegerField(null=True)),
                ('serial', models.CharField(max_length=30, null=True)),
                ('persons', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='booking_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='hotels',
            name='owners',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking_app.hotelowner'),
        ),
        migrations.CreateModel(
            name='PersonComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('time_comment', models.DateTimeField(auto_now_add=True)),
                ('person_rating', models.PositiveIntegerField(null=True)),
                ('hotels', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking_app.hotels')),
                ('persons', models.ManyToManyField(to='booking_app.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['guest_rating'], name='guest_rating_idx'),
        ),
        migrations.AddField(
            model_name='hotelscomment',
            name='persons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_comments', to='booking_app.person'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='persons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking_app.person'),
        ),
        migrations.AddIndex(
            model_name='hotels',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
    ]
