# Generated by Django 5.0.4 on 2024-06-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_alter_user_age_feedback_room_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to='users_photo/', verbose_name='photo'),
        ),
    ]
